// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infra

import (
	"github.com/joisandresky/go-chi-clean-starter/internal/application/usecases"
	"github.com/joisandresky/go-chi-clean-starter/internal/infra/repositories"
	"github.com/joisandresky/go-chi-clean-starter/internal/presentation/api"
	"github.com/joisandresky/go-chi-clean-starter/internal/presentation/middleware"
)

// Injectors from wire.go:

func BuildServer() *ServerBuilder {
	config := ConfigProvider()
	sugaredLogger := LoggerProvider()
	db := PgGormProvider(config, sugaredLogger)
	client := RedisProvider(config, sugaredLogger)
	testMiddleware := middleware.NewTestMiddleware(sugaredLogger)
	postRepository := repositories.NewPgPostRepository(db)
	postUsecase := usecases.NewPostUsecase(postRepository)
	postHttpApi := api.NewPostHttpApi(postUsecase)
	mux := api.SetupRoutes(testMiddleware, postHttpApi)
	serverBuilder := NewServer(config, sugaredLogger, db, client, mux)
	return serverBuilder
}
